### ISSUE TITLE
Code base displays linker errors with latest Good SDK 1.10.xxxx

### ISSUE THREAD

**Issue by Sincerus** [jhawkinsatgood/contributor#1]
If the reader follows the docs on page 10 for the iOS SDK they should be 'good' to go.  :-)

There are additional libraries required now that are not being used in this Good xcode version on GitHub.

If you do a 'new' Good Console app, via xCode 'New Project', you can drag and drop the code and then just replace the key bundle IDs as needed.

**Comment by jhawkinsatgood** [comment]
Thank you for reporting this. I haven't updated the contributor code for the latest GD SDK release yet. This issue should be resolved when I do that.

I believe the only new required library should be LocalAuthentication.framework
The complete list of libraries is on the Good Developer Network here:
https://community.good.com/view-doc.jspa?fileName=licenses.html&docType=api

**Comment by Sincerus** [comment]
Mr Hawkins,

You are most welcome.

Thanks for the example on how to have GOOD work in the background instead of the APP Delegate.

The LazyTable video on Vimeo was very helpful.

I’ve been trying to get the Oracle OBI code and GOOD to play well together.

GOOD needs to work with a true AppDelegate and Oracle’s code makes you ’sub-class’ their AppDelegate.

Here is their code base:  http://www.oracle.com/technetwork/middleware/bi-enterprise-edition/downloads/bi-mobile-security-toolkit-1872818.html http://www.oracle.com/technetwork/middleware/bi-enterprise-edition/downloads/bi-mobile-security-toolkit-1872818.html

http://docs.oracle.com/cd/E52471_01/doc.1111/e59495/toc.htm#CHDIEJHF http://docs.oracle.com/cd/E52471_01/doc.1111/e59495/toc.htm#CHDIEJHF

That doc explains how to set it up.  It has been an interesting problem to solve to say the least.

Been looking at this problem all week.  Tomorrow I test my last approach or I go with plan B which is a ‘wrapped’ version.  The wrapped version forces the users to login again via the web since I can’t inject an SSO cookie.

Kind regards,

Ed

**Comment by jhawkinsatgood** [comment]
Sorry, I don't have any contributor code for using Good Dynamics with Oracle OBI. You could try asking or searching on the Good Dynamics Network support forum. It is here:
https://community.good.com/community/gdn/support

**Comment by jhawkinsatgood** [comment]
The contributor code is now updated for the latest GD SDK releases. It's here on GitHub:
[https://github.com/jhawkinsatgood/gdcontributor](https://github.com/jhawkinsatgood/gdcontributor)
I created a new repository in order to implement a name change, from contributor to gdcontributor.
